print("Enter your name ")
x=input()
print("Enter your lab grade ")
y=int(input())
print("Enter your midterm grade ")
z=int(input())
print("Enter your final grade ")
v=int(input())
total=(25*y/100)+(35*z/100)+(40*v/100)
print("Name: " + x)
print("Lab: ")
print(y)
print("Midterm: ")
print(z)
print("Final: ")
print(v)
print("Total is: ")
print(total)
